### ISSUE TITLE
[Da Nang] Hướng dẫn cài đặt môi trường

### ISSUE THREAD

**Issue by vinhnglx** [RubyGirlsVN/rubygirls.org.vn#11]
https://docs.google.com/presentation/d/1JtypuEuV7Ie18OPdNqRXwcbZzLrRpIHxtzMfW7sEj-Q/edit?usp=sharing

**Comment by runlevel5** [comment]
cái này em phải hướng dẫn chi tiết làm gì với USB

**Comment by vinhnglx** [comment]
em sẽ nói nữa anh :) ....
